/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function add(x: number, y: number): number;
export interface MorphemeJs {
  surface: string;
  partOfSpeech: Array<string>;
  normalizedForm: string;
}
export class SudachiJs {
  static create(
    configFile?: string | undefined | null,
    resourceDir?: string | undefined | null,
    dictionaryPath?: string | undefined | null,
    mode?: string | undefined | null
  ): SudachiJs;
  run(input: string): Array<MorphemeJs>;
  destroy(): void;
}
