/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function add(x: number, y: number): number
export class SudachiJs {
  static create(configFile?: string | undefined | null, resourceDir?: string | undefined | null, dictionaryPath?: string | undefined | null, mode?: string | undefined | null): SudachiJs
  run(input: string): string
  destroy(): void
}
