[package]
name = "sudachi_wasm"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sudachi = { git = "https://github.com/WorksApplications/sudachi.rs.git", tag = "v0.6.6" }
wasm-bindgen = "0.2.83"
