name: ci
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.12.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - run: pnpm i --frozen-lockfile
      - run: npm run lint:check
      - run: npm run tsc

  build-napi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.12.1"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - run: npm -C sudachi.js run build
      - run: pnpm i --frozen-lockfile
      - run: npm run build

  # based on https://github.com/rustwasm/wasm-pack/blob/10f30be713f03eae68df21b34a220c03b45d871f/.github/workflows/test.yml
  build-wasm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # node
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            sudachi.wasm/target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('sudachi.wasm/Cargo.lock') }}
      # build
      - run: npm -C sudachi.wasm ci
      - run: npm -C sudachi.wasm run build
